//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public string FacturaId { get; set; }
        public string Productos { get; set; }
        public float Cantidad { get; set; }
        public string PrecioUnitario { get; set; }
        public string Total { get; set; }
        public string Abonos { get; set; }
        public string Saldo { get; set; }
        public bool Cancelada { get; set; }
        public int PersonaId { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
