//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoId { get; set; }
        public string Nombre { get; set; }
        public int EmpaqueId { get; set; }
        public int TamanioId { get; set; }
    
        public virtual Empaque Empaque { get; set; }
        public virtual Tamanio Tamanio { get; set; }
    }
}
